name: voxelpaint
base: core22
version: '2.3.3'
license: GPL-2.0-only
summary: Paint in 3D using voxels!
description: |
  Mouse locks when you click on the game window, press ESCAPE or TAB to unlock the mouse.
  
  W,A,S,D = Move around based on relative orientation to X and Y.
  SPACE + L-SHIFT = Move up and down relative Z.
  Left Click / R-SHIFT = Place node.
  Right Click / R-CTRL = Delete node.
  Q / Middle Click = Clone texture of pointed node.
  R = Places node at your current position.
  E / F / Mouse4 = Toggle player fast speed on and off.
  1-7 = Change move speed for selected fast state.
  X + C / Slash + Quote = Change texture of pointed node.
  T = Resets player state to start.
  G = Gravity on/off.
  P = Toggle pitch lock.
  F3 = Save. (auto saves on exit or idle for more than 3 minutes)
  F8 = Load. (will erase what you have done since the last save)
  F10 = Export the VoxelPaint data to a zip file in $HOME/EXPORTS.

  To multiselect click and drag with Middle Mouse or Q. Fill the nodes with B or delete them with N. Middle Scroll or X+C to change texture. V to paste selected nodes to pointed position.

  Arrow Keys can be used to move the view around.
  
  Your state is automatically saved on exit.

  Sensitivity as the 1st command line parameter default is 0.003 `./voxelpaintpro 0.003`.

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]
  - build-on: [armhf]
    build-for: [armhf]

apps:
  voxelpaint:
    extensions: [gnome]
    command: voxelpaint
    plugs:
    - desktop
    - desktop-legacy
    - gsettings
    - opengl
    - wayland
    - x11
    - home
    environment:
      HOME: /home/$USER

parts:
  voxelpaint:
    source: https://github.com/mrbid/voxelpaint
    source-type: git
    plugin: make
    source-subdir: snap
    build-packages:
    - libsdl2-dev
    stage-packages:
    - libsdl2-2.0-0
